<?php

// Exit if accessed directly
if( !defined( 'ABSPATH' ) ) {
  exit;
}

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */
$template_directory = get_template_directory();
require( $template_directory . '/core/includes/functions.php' );
require( $template_directory . '/core/includes/functions-update.php' );
require( $template_directory . '/core/includes/functions-sidebar.php' );
require( $template_directory . '/core/includes/functions-install.php' );
require( $template_directory . '/core/includes/functions-admin.php' );
require( $template_directory . '/core/includes/functions-extras.php' );
require( $template_directory . '/core/includes/functions-extentions.php' );
require( $template_directory . '/core/includes/theme-options/theme-options.php' );
require( $template_directory . '/core/includes/post-custom-meta.php' );
require( $template_directory . '/core/includes/tha-theme-hooks.php' );
require( $template_directory . '/core/includes/hooks.php' );
require( $template_directory . '/core/includes/version.php' );
require( $template_directory . '/core/includes/upsell/theme-upsell.php' );
require( $template_directory . '/pro/init.php' );
require($template_directory . '/dashboard-widget.php');


/* For excerpt accepting html tags - start */
function excerpt_allowedtags() {
    // Add custom tags to this string
        return '<script>,<style>,<br>,<em>,<i>,<ul>,<ol>,<li>,<a>,<p>,<img>,<video>,<audio>,<strong>,<b>,<div>,<span>,<select>,<option>'; 
    }

if ( ! function_exists( 'responsivepro_trim_excerpt' ) ) : 

    function responsivepro_trim_excerpt($repmob_excerpt) {
    $raw_excerpt = $repmob_excerpt;
        if ( '' == $repmob_excerpt ) {

            $repmob_excerpt = get_the_content('');
            $repmob_excerpt = strip_shortcodes( $repmob_excerpt );
            $repmob_excerpt = apply_filters('the_content', $repmob_excerpt);
            $repmob_excerpt = str_replace(']]>', ']]&gt;', $repmob_excerpt);
            $repmob_excerpt = strip_tags($repmob_excerpt, excerpt_allowedtags()); /*IF you need to allow just certain tags. Delete if all tags are allowed */

            //Set the excerpt word count and only break after sentence is complete.
                $excerpt_word_count = 75;
                $excerpt_length = apply_filters('excerpt_length', $excerpt_word_count); 
                $tokens = array();
                $excerptOutput = '';
                $count = 0;

                // Divide the string into tokens; HTML tags, or words, followed by any whitespace
                preg_match_all('/(<[^>]+>|[^<>\s]+)\s*/u', $repmob_excerpt, $tokens);

                foreach ($tokens[0] as $token) { 

                    if ($count >= $excerpt_length && preg_match('/[\,\;\?\.\!]\s*$/uS', $token)) { 
                    // Limit reached, continue until , ; ? . or ! occur at the end
                        $excerptOutput .= trim($token);
                        break;
                    }

                    // Add words to complete sentence
                    $count++;

                    // Append what's left of the token
                    $excerptOutput .= $token;
                }

            $repmob_excerpt = trim(force_balance_tags($excerptOutput));

                $excerpt_end = ' <a href="'. esc_url( get_permalink() ) . '">' . '&nbsp;&raquo;&nbsp;' . sprintf(__( 'Read more about: %s &nbsp;&raquo;', 'responsive' ), get_the_title()) . '</a>'; 
                $excerpt_more = apply_filters('excerpt_more', ' ' . $excerpt_end); 

                $repmob_excerpt .= $excerpt_more; /*Add read more in new paragraph */

            return $repmob_excerpt;   

        }
        return apply_filters('responsivepro_trim_excerpt', $repmob_excerpt, $raw_excerpt);
    }

endif; 

remove_filter('get_the_excerpt', 'wp_trim_excerpt');
add_filter('get_the_excerpt', 'responsivepro_trim_excerpt'); 
/* For excerpt accepting html tags - end */



function responsivepro_title_setup() {

   add_theme_support( 'title-tag' );
}

add_action( 'after_setup_theme', 'responsivepro_title_setup' );
