<?php

// Exit if accessed directly
if( !defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Responsive Pro Initialization
 *
 * Initialization for Responsive Pro
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category Responsive Pro
 * @package  Responsive Pro
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
$template_directory = get_template_directory();
require( $template_directory . '/pro/functions.php' );
require( $template_directory . '/pro/options/options-customizer.php' );
require( $template_directory . '/pro/options/options.php' );
require( $template_directory . '/pro/classes/Responsive_Pro_Options.php' );