<?php
/**
 * Responsive Pro Options
 *
 * A class that extends the core option class and adds more functionality
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

Class Responsive_Pro_Options extends Responsive_Options {

	/**
	 * Creates upload option
	 *
	 * @param $args array
	 *
	 * @return string
	 */
	protected function upload( $args ) {
		extract( $args );

		$value = ( !empty( $this->responsive_options[$id] ) ) ? $this->responsive_options[$id] : '';
		if (isset($disable) && $disable == 'true')
			$visibility = 'disabled="disabled"';
		else
			$visibility = "";
		
		$html = '<div class="grid col-700 media-upload">
                    <input id="responsive_theme_options_' . $id . '" name="responsive_theme_options[' . $id . ']"' . $visibility . ' type="text" value="' . esc_attr( $value ) . '" />
                    <label class="description" ' . $visibility .' for="responsive_theme_options[' . $id . ']">' . $description . '</label>
                    <button class="button upload" name="responsive_theme_options[' . $id . ']_upload" ' . $visibility . ' id="responsive_theme_options_' . $id . '_upload">' . $button . '</button>
                    </div>
                    <div class="grid col-220 fit media-upload">';
		if( $value != '' ) {
			$html .= '<img src="' . esc_url( $value ) . '" class="upload-image"/>';
		}

		$html .= '</div>';

		return $html;
	}

	/**
	 * Creates option section for plugin support
	 *
	 * @param $args array
	 *
	 * @return string
	 */
	protected function plugins( $args ) {
		extract( $args );
		
		$plugin   = $url;
		$icon     = '<img class="plugins-icon" src="' . get_template_directory_uri() . '/pro/options/lib/images/' . $id . '.png" />';
		$icon_neg = '<img class="plugins-icon" src="' . get_template_directory_uri() . '/pro/options/lib/images/' . $id . '-neg.png" />';
		
		$installed_plugins = get_plugins();
		
		$html = '<div class="plugin-check" id="' . $id . '">';
		
		if( isset( $installed_plugins[$plugin] ) ) {
			if( is_plugin_active( $plugin ) ) {
				$html .= $icon . '<a href="' . admin_url( $settings_page ) . '">' . $active . '</a>';
			}
			else {
				$html .= $icon_neg . '<a href="' . admin_url( 'plugins.php' ) . '">' . $activate . '</a>';
			}
		}
		else {
			$html .= $icon_neg . '<a href="' . $this->reponsive_pro_plugin_install_link( $id ) . '">' . $install . '</a>';
		}
		
		$html .= '</div>';
		
		return $html;
	}

	protected function reponsive_pro_plugin_install_link( $slug ) {
		include_once ABSPATH . 'wp-admin/includes/plugin-install.php';

		return wp_nonce_url( self_admin_url( 'update.php?action=install-plugin&plugin=' . $slug ), 'install-plugin_' . $slug );
	}

	protected function radio_grid( $args ){

		extract($args);
	
		$saved_value = ( !empty( $this->responsive_options[$id] ) ) ? $this->responsive_options[$id] : 'default-layout';

		$html = '<div class="responsive-layouts-wrapper">';

		if( !empty($values) ){
						
			foreach ($values as $radio_input => $key ) {				
				
				$grid_layout_image = get_template_directory_uri().'/pro/lib/images/'. $radio_input .'.png';
				if (isset($disable) && $disable == 'true')
				{				
					$style = 'style="border:none;cursor:default;"';
					$visibility = 'disabled="disabled"';
				}
				else
					$visibility = "";	
				
				$html .= '<div class="radio-grids-option-wrapper">';
				$html .= '<div class="radio-grid-description">' . $key . '</div>';
				$html .= '<img class="'.$selected.'" src = "' . $grid_layout_image . '" ' . $style . ' />';
				$html .= '<input type="radio"' . $visibility .' id="' . $radio_input . '" name="responsive_theme_options[' . $id .']" class="radio-grids" ' . $checked . ' value="' . $radio_input .'" style="display: none;">';
				$html .= '</div>';
			}
		}

		$html .= '</div>';		

		return $html;
	}
}